export const COLOUR_PRIMARY = "#0B132B"
export const COLOUR_SECONDARY = "#028090"
export const COLOUR_TERTIARY = "#DE3C4B"
export const COLOUR_DARK = "#285F6F"
export const COLOUR_SUBTLE = "#AAB3A4"
export const COLOUR_ACCENT = "#EAECCA"
export const COLOUR_LIGHT = "#FAFCFE"

export const COLOUR_COTTON_CANDY = "#F7E1E3"
export const COLOUR_MINTED = "#BCD9D4"
export const COLOUR_SUNSHINE = "#F7EAC7"
export const COLOUR_PEACHY = "#F9D5C7"
export const COLOUR_FLUFF = "#E8D7E1"
export const COLOUR_SKY = "#D5F7F3"