export const COLOUR_PRIMARY = "#0B132B"
export const COLOUR_SECONDARY = "#028090"
export const COLOUR_TERTIARY = "#DE3C4B"
export const COLOUR_DARK = "#285F6F"
export const COLOUR_SUBTLE = "#AAB3A4"
export const COLOUR_ACCENT = "#EAECCA"
export const COLOUR_LIGHT = "#FAFCFE"