import { PestTypes } from '../../types/SpeciesType';

export const PestTypesMap: Array<{ id: PestTypes; name: string }> = [
  { id: 'ABIOTIC_DISORDER', name: 'Abiotic Disorder' },
  { id: 'ADELGIDS', name: 'Adelgids' },
  { id: 'ANTHRACNOSE', name: 'Anthracnose' },
  { id: 'APHIDS', name: 'Aphids' },
  { id: 'BACTERIAL_LEAF_SPOT', name: 'Bacterial Leaf Spot' },
  { id: 'BEETLES', name: 'Beetles' },
  { id: 'BLIGHT', name: 'Blight' },
  { id: 'CANKER', name: 'Canker' },
  { id: 'CATERPILLAR', name: 'Caterpillar' },
  { id: 'CROWN_ROT', name: 'Crown Rot' },
  { id: 'CUTWORM', name: 'Cutworm' },
  { id: 'DEER_RESISTANT', name: 'Deer Resistant' },
  { id: 'DIEBACK', name: 'Dieback' },
  { id: 'DIPTERA_TRUE_FLIES', name: 'Diptera True Flies' },
  { id: 'DISEASE_RESISTANT', name: 'Disease Resistant' },
  { id: 'DROUGHT_RESISTANT', name: 'Drought Resistant' },
  { id: 'EARWIGS', name: 'Earwigs' },
  { id: 'FUNGAL_LEAF_SPOT', name: 'Fungal Leaf Spot' },
  { id: 'GALLS', name: 'Galls' },
  { id: 'HEART_ROT', name: 'Heart Rot' },
  { id: 'HETEROPTERA_TRUE_BUGS', name: 'Heteroptera True Bugs' },
  { id: 'LEAFHOPPER', name: 'Leafhopper' },
  { id: 'LEAF_MINER_INSECT', name: 'Leaf Miner Insect' },
  { id: 'LEAF_SCORCH', name: 'Leaf Scorch' },
  { id: 'MEALYBUGS', name: 'Mealybugs' },
  { id: 'MILDEW', name: 'Mildew' },
  { id: 'MISTLETOE', name: 'Mistletoe' },
  { id: 'MITES', name: 'Mites' },
  { id: 'MOLD', name: 'Mold' },
  { id: 'NEEDLE_CAST', name: 'Needle Cast' },
  { id: 'NEMATODES', name: 'Nematodes' },
  { id: 'PEST_RESISTANT', name: 'Pest Resistant' },
  { id: 'PSYLLIDS', name: 'Psyllids' },
  { id: 'RABBIT_RESISTANT', name: 'Rabbit Resistant' },
  { id: 'RODENTS', name: 'Rodents' },
  { id: 'ROOT_ROT', name: 'Root Rot' },
  { id: 'RUST', name: 'Rust' },
  { id: 'SAP_ROT', name: 'Sap Rot' },
  { id: 'SAWFLIES', name: 'Sawflies' },
  { id: 'SCALE_INSECTS', name: 'Scale Insects' },
  { id: 'SLUGS', name: 'Slugs' },
  { id: 'SNAILS', name: 'Snails' },
  { id: 'SPITTLEBUG', name: 'Spittlebug' },
  { id: 'STEM_BORER_INSECTS', name: 'Stem Borer Insects' },
  { id: 'THRIPS', name: 'Thrips' },
  { id: 'VIRUS', name: 'Virus' },
  { id: 'WEEVILS', name: 'Weevils' },
  { id: 'WHITEFLY', name: 'Whitefly' },
  { id: 'WILT', name: 'Wilt' },
  { id: 'WOOD_DEFORMITY', name: 'Wood Deformity' },
  { id: 'UNKNOWN', name: 'Unknown' },
];
